### ISSUE TITLE
Schedule looks wierd when there are too many classes at the same time

### ISSUE THREAD

**Issue by LuisDuarte1** [NIAEFEUP/nitsig#145]
![image](https://github.com/NIAEFEUP/nitsig/assets/24589619/d5f08973-bf99-4efe-9e4c-04c0f67a5774)

**Comment by toni-santos** [comment]
The schedule page has since been refactored by Sigarra, meaning our solution no longer works :face_with_head_bandage: . Perhaps we should look into these changes...
