### ISSUE TITLE
Add support for CSS nesting

### ISSUE THREAD

**Issue by ttoino** [NIAEFEUP/nitsig#167]
Our current CSS code is extremely messy and hard to reason about. This can be mitigated by introducing CSS nesting, with something like Sass or PostCSS.

**Comment by toni-santos** [comment]
As of now CSS3 can do [nesting](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting) ([and it's pretty well supported](https://caniuse.com/css-nesting)), something that we should most likely look into refactoring it into our codebase. Still Sass can be pretty useful and something we might want to adopt.
